### ISSUE TITLE
Add support for LYWSD02 and MHO-C303

### ISSUE THREAD

**Issue by max-koptev** [crazymikefra/HA_ATC_Time#2]
Dear Mike! Thanks for your work, I installed this component and it works great with my MJWSD05MMC device. Could you add support for LYWSD02 and MHO-C303 bluetooth clocks from Xiaomi? They use the same protocol and can be synchronized for example in this project: https://saso5.github.io/LYWSD02-clock-sync/
Now I'm setting them up using esphome installed on the esp32 board, but it doesn't seem reliable.
Setting them up using your service would be very convenient.

**Comment by crazymikefra** [comment]
Hi Max,

For LYWSD02, i think it is possible with the code you provide me.
In this code, i have the UUID to call for the update.
If i had a model selector in service call, i think i can dialog with both models.

For MHO-C303, is it the same as LYWSD02 or another one ?
I need to make a search on this model.

Regards.

**Comment by crazymikefra** [comment]
@max-koptev Can you launch this command on your homeassistant ?
bluetoothctl info < MAC Adress of your device >

You should have informations like this in return :
![image](https://github.com/crazymikefra/HA_ATC_Time/assets/92884668/698d974e-a965-4b3e-b7f7-e69388fb7c1f)

Can you make this for each of your models ?

**Comment by crazymikefra** [comment]
@max-koptev : I have added a new service to help analyse your devices :
![image](https://github.com/crazymikefra/HA_ATC_Time/assets/92884668/a1fd049d-c7f5-4dc5-8b67-680e19224e8c)

You will obtain the result in logs like this :
![image](https://github.com/crazymikefra/HA_ATC_Time/assets/92884668/71cf610e-7d36-4e46-b7a7-7633dbec396d)

Can you send me those results for your devices ?

Regards.

**Comment by crazymikefra** [comment]
Sorry. I close this issue since no answer.
